### ISSUE TITLE
Plotting requirements

### ISSUE THREAD

**Issue by henryiii** [conda-forge/hist-feedstock#5]
Let's split this up into hist-core and hist - where hist-core has the minimum requirements, and hist has `hist[plot]` requirements. An alternative is to just not provide hist-core yet (at least until requested), and just provide hist with the plotting requirements included. Currently it seems a little broken that you can't plot after installing it (there are no extras in conda, like there are in pip).

**Comment by chrisburr** [comment]
I think `hist-base` would fit better with other package naming in conda-forge (e.g. `matplotlib-base` and `jupyterhub-base`).
